### ISSUE TITLE
Doesn't work with Cytoscape 3.2.0

### ISSUE THREAD

**Issue by anault** [cytoscape/cytoscape.js-edgehandles#85]
`cytoscape.js-edgehandles` doesn't work with the latest version of Cytoscape (3.2.0), which was published 2 hours ago.

Here's the [edgehandle demo](https://codepen.io/anault/pen/JyMPLe) in codepen.

Here's the error: 
```
Uncaught TypeError: node.hasClass is not a function
    at u.dragNodeHandler (cytoscape-edgehandles.js:972)
    at cytoscape.min.js:1
    at h (cytoscape.min.js:1)
    at r.u.emit.u.trigger (cytoscape.min.js:1)
    at u.emit (cytoscape.min.js:10)
    at cytoscape.min.js:1
    at h (cytoscape.min.js:1)
    at r.u.emit.u.trigger (cytoscape.min.js:1)
    at u.emit (cytoscape.min.js:8)
    at cytoscape.min.js:10
```

**Comment by maxkfranz** [comment]
It's a problem with both the extension and the main lib.  The lib doesn't support `this` properly in event callbacks in 3.2, and the extension shouldn't really be using `this` anyway.  That feature was never really formally documented anywhere; it was just to be nice for people used to how the jQuery API works.

Anyway, we have a fix for the main lib -- confirmed by new unit tests and manual testing with this extension -- and we'll push 3.2.1 to npm today.  In the meantime, you can roll back to 3.1.x or patch the extension to use `event.target` instead of `this`.

**Comment by maxkfranz** [comment]
Ref : https://github.com/cytoscape/cytoscape.js/issues/1930

**Comment by anault** [comment]
Fixed in Cytoscape 3.2.1
